name: Build and publish python hello-world

on: [push]

env:
  FILEPATH_PYTHON_MAIN: "src/main.py"
  GH_REGISTRY: "ghcr.io"

jobs:
  python-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          ruff check
        continue-on-error: true

      - name: Test with Coverage Unittest
        run: |
          coverage run -m unittest discover -p '*_test.py'
          coverage report -m --omit="*_test.py"
        continue-on-error: true

      - name: Run python program
        run: |
          echo "-------- RUN 1 --------"
          python ${{ env.FILEPATH_PYTHON_MAIN }}
          echo "-------- RUN 2 --------"
          python ${{ env.FILEPATH_PYTHON_MAIN }}

      - name: Upload packaged python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-hello-world-artifacts-${{ matrix.python-version }}
          path: .

  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - python-build
    strategy:
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
    steps:
      - name: Download packaged python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-hello-world-artifacts-${{ matrix.python-version }}

      - name: Authenticate to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Authenticate to github cr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tags and labels metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
              izzkhair/python-hello-world
              ghcr.io/${{ github.repository }}

      - name: Build docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.python-version }}
          labels: ${{ steps.meta.outputs.labels }}-${{ matrix.python-version }}
          build-args: |
            BASE_DOCKER_IMAGE=${{ matrix.python-version }}

#      - name: Scan container for vulnerabilities
#        uses: crazy-max/ghaction-container-scan@v3
#        with:
#          image: ${{ steps.meta.outputs.tags }}-${{ matrix.python-version }}

#      - name: Run docker image
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ steps.meta.outputs.tags }}-${{ matrix.python-version }}
#          run: python ${{ env.FILEPATH_PYTHON_MAIN }}

      - name: Push docker image to docker hub and github cr
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.python-version }}
          labels: ${{ steps.meta.outputs.labels }}-${{ matrix.python-version }}
          build-args: |
            BASE_DOCKER_IMAGE=${{ matrix.python-version }}
